### ISSUE TITLE
Xaml 文件不见了

### ISSUE THREAD

**Issue by Axure** [MichaelSuen-thePointer/QBox#1]
MVVM_Model 分支

> 严重性  代码  说明  项目  文件  行
> 错误      未能找到文件“QBox\StartPage.xaml”。  QBox        

，

> 严重性  代码  说明  项目  文件  行
> 错误  CS1061  “App”未包含“InitializeComponent”的定义，并且找不到可接受第一个“App”类型参数的扩展方法“InitializeComponent”(是否缺少 using 指令或程序集引用?) QBox    QBox\App.xaml.cs    36

，

> 严重性  代码  说明  项目  文件  行
> 错误  CS1061  “DownloadFileView”未包含“InitializeComponent”的定义，并且找不到可接受第一个“DownloadFileView”类型参数的扩展方法“InitializeComponent”(是否缺少 using 指令或程序集引用?)   QBox    QBox\DownloadFileView.xaml.cs   27

**Comment by MichaelSuen-thePointer** [comment]
收到，上完课处理

发件人: Hu Zheng [mailto:notifications@github.com] 
发送时间: 2015年10月19日 3:21
收件人: MichaelSuen-thePointer/QBox QBox@noreply.github.com
主题: [QBox] Xaml 文件不见了 (#1)

MVVM_Model 分支

严重性 代码 说明 项目 文件 行
错误 未能找到文件“QBox\StartPage.xaml”。 QBox 

，

严重性 代码 说明 项目 文件 行
错误 CS1061 “App”未包含“InitializeComponent”的定义，并且找不到可接受第一个“App”类型参数的扩展方法“InitializeComponent”(是否缺少 using 指令或程序集引用?) QBox QBox\App.xaml.cs 36

，

严重性 代码 说明 项目 文件 行
错误 CS1061 “DownloadFileView”未包含“InitializeComponent”的定义，并且找不到可接受第一个“DownloadFileView”类型参数的扩展方法“InitializeComponent”(是否缺少 using 指令或程序集引用?) QBox QBox\DownloadFileView.xaml.cs 27
